name: Docs
on:
  push:
    branches:
      - main
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          submodules: true

      - uses: cachix/install-nix-action@v20
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.8.0pre20220311_d532269/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm recursive-nix

      - name: Generate content
        run: nix -Lv develop -c python build.py

      - name: Generate Publish
        run: |
          nix -Lv develop -c hugo --minify
          cp -rf ./public/posts/index.html ./public/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ./public
